apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hyperswitch-secrets
  namespace: hyperswitch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: hyperswitch-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: hyperswitch/infra
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: hyperswitch/infra
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: hyperswitch/infra
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: hyperswitch/infra
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: hyperswitch/infra
        property: DB_PASSWORD
    - secretKey: REDIS_HOST
      remoteRef:
        key: hyperswitch/infra
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: hyperswitch/infra
        property: REDIS_PORT
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: hyperswitch/infra
        property: HYPERSWITCH_ADMIN_API_KEY
    - secretKey: JWT_SECRET
      remoteRef:
        key: hyperswitch/infra
        property: JWT_SECRET
