apiVersion: v1
kind: Namespace
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/part-of: hyperswitch-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: cart-service
  labels:
    app.kubernetes.io/part-of: hyperswitch-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: inventory-service
  labels:
    app.kubernetes.io/part-of: hyperswitch-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: notification-service
  labels:
    app.kubernetes.io/part-of: hyperswitch-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: order-service
  labels:
    app.kubernetes.io/part-of: hyperswitch-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-service
  labels:
    app.kubernetes.io/part-of: hyperswitch-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: hyperswitch
  labels:
    app.kubernetes.io/part-of: hyperswitch-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: hyperswitch-platform
