apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notification-service-secrets
  namespace: notification-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: SQS_NOTIFICATION_QUEUE_URL
      remoteRef:
        key: hyperswitch/infra
        property: SQS_NOTIFICATION_QUEUE_URL
    - secretKey: AWS_REGION
      remoteRef:
        key: hyperswitch/infra
        property: AWS_REGION
