apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification-service
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: notification-service
